drop table if exists "full-stack-ecommerce"."order_item";
DROP TABLE IF EXISTS "full-stack-ecommerce"."orders";
DROP TABLE IF EXISTS "full-stack-ecommerce"."customer";
DROP TABLE IF EXISTS "full-stack-ecommerce"."address";
drop table if exists "full-stack-ecommerce"."product";
drop table if exists "full-stack-ecommerce"."product_category";


CREATE TABLE "full-stack-ecommerce"."product_category"(	
   id INT GENERATED ALWAYS AS IDENTITY,
   category_name VARCHAR(255) NOT NULL,
   PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS "full-stack-ecommerce"."product"(
	id INT GENERATED ALWAYS AS IDENTITY,
  	sku VARCHAR(255) DEFAULT NULL,	
  	name VARCHAR(255) DEFAULT NULL, 
  	description VARCHAR(255) DEFAULT NULL,
  	unit_price DECIMAL(13,2),
  	rating INT default 2,
  	image_url VARCHAR(255) DEFAULT NULL,
  	active bit default CAST(1 AS bit),
  	units_in_stock INT default null,
  	date_created Date, 
  	last_updated Date,
  	category_id INT not null,
  	PRIMARY KEY(id),
	CONSTRAINT fk_category
		FOREIGN KEY(category_id) 
		REFERENCES "full-stack-ecommerce".product_category(id)	
);

CREATE TABLE "full-stack-ecommerce"."address" (
  id INT GENERATED ALWAYS AS IDENTITY,
  city varchar(255) DEFAULT NULL,
  country varchar(255) DEFAULT NULL,
  state varchar(255) DEFAULT NULL,
  street varchar(255) DEFAULT NULL,
  zip_code varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE "full-stack-ecommerce"."customer"  (
  id INT GENERATED ALWAYS AS IDENTITY,
  first_name varchar(255) DEFAULT NULL,
  last_name varchar(255) DEFAULT NULL,
  email varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE "full-stack-ecommerce"."orders" (
  id INT GENERATED ALWAYS AS IDENTITY,
  order_tracking_number varchar(255) DEFAULT NULL,
  total_price decimal(19,2) DEFAULT NULL,
  total_quantity int DEFAULT NULL,
  billing_address_id bigint DEFAULT NULL,
  customer_id int DEFAULT NULL,
  shipping_address_id int DEFAULT NULL,
  status varchar(128) DEFAULT NULL,
  date_created Date DEFAULT NULL,
  last_updated Date DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_customer_id FOREIGN KEY (customer_id) REFERENCES "full-stack-ecommerce".customer(id),
  CONSTRAINT FK_billing_address_id FOREIGN KEY (billing_address_id) REFERENCES "full-stack-ecommerce".address(id),
  CONSTRAINT FK_shipping_address_id FOREIGN KEY (shipping_address_id) REFERENCES "full-stack-ecommerce".address(id)
);

CREATE TABLE "full-stack-ecommerce"."order_item"(
  id INT GENERATED ALWAYS AS IDENTITY,
  image_url varchar(255) DEFAULT NULL,
  quantity int DEFAULT NULL,
  unit_price decimal(19,2) DEFAULT NULL,
  order_id int DEFAULT NULL,
  product_id int DEFAULT NULL,
  PRIMARY KEY (id),
  CONSTRAINT FK_order_id FOREIGN KEY (order_id) REFERENCES "full-stack-ecommerce".orders(id),
  CONSTRAINT FK_product_id FOREIGN KEY (product_id) REFERENCES "full-stack-ecommerce".product(id)
);

-- -----------------------------------------------------
-- Categories
-- -----------------------------------------------------
INSERT INTO "full-stack-ecommerce".product_category(category_name) VALUES ('Vegetables');
INSERT INTO "full-stack-ecommerce".product_category(category_name) VALUES ('Fruits');
INSERT INTO "full-stack-ecommerce".product_category(category_name) VALUES ('Dairy');
INSERT INTO "full-stack-ecommerce".product_category(category_name) VALUES ('Grains');


-- -----------------------------------------------------
-- BVEGETABLES
-- -----------------------------------------------------

INSERT INTO "full-stack-ecommerce"."product" (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1000', E'Carrots', E'Fresh carrots. Carrots received from the best country that produces the freshest carrots. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1000.png' ,cast(1 as bit), 100, 14.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1001', E'Cucumber', E'Fresh Cucumber. Cucumber received from the best country that produces the freshest cucumbers. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1001.png' ,cast(1 as bit), 100, 20.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1002', E'Zucchini', E'Fresh Zucchini. Zucchini received from the best country that produces the freshest Zucchinis. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1002.png' ,cast(1 as bit), 100, 14.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1003', E'Pumpkin', E'Big and fresh Pumpkin. Pumpkin received from the best country that produces the freshest Pumpkins. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1003.png' ,cast(1 as bit), 100, 13.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1004', E'Mushroom', E'Best and tasty Mushrooms. Mushrooms received from the best country that produces the freshest Mushrooms. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1004.png' ,cast(1 as bit), 100, 18.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1005', E'Red Onion', E'Specially harvested Red Onions. Onions received from the best country that produces the freshest onions. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1005.png' ,cast(1 as bit), 100, 23.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1006', E'Pepper', E'Fresh peppers. Peppers received from the best country that produces the freshest peppers. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1006.png' ,cast(1 as bit), 100, 14.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1007', E'Cooking Potatoes', E'Potatoes specifically grown for cooking. Potatoes recently flown from the best country that produces the freshest Potatoes. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1007.png' ,cast(1 as bit), 100, 16.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1008', E'Lady Fingers', E'Green Lady Fingers. Lady fingers received from the best country that produces the freshest lady Fingers. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1008.png' ,cast(1 as bit), 100, 25.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1009', E'EggPlant', E'Fresh eggplant. Eggplant received from the best country that produces the freshest eggplants. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1009.png' ,cast(1 as bit), 100, 23.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1010', E'Avocado', E'Fresh Avocado. Avocados received from the best country that produces the freshest avocados. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1010.png' ,cast(1 as bit), 100, 24.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1011', E'Brocoli', E'Fresh brocoli. Brocoli received from the best country that produces the freshest Brocoli. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1011.png' ,cast(1 as bit), 100, 19.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1012', E'Sweet Potato', E'Sweet potato. Potatoes received from the best country that produces the freshest sweet potatoes. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1012.png' ,cast(1 as bit), 100, 24.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1013', E'Radish', E'Fresh radish. Radish received from the best country that produces the freshest radishes. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1013.png' ,cast(1 as bit), 100, 19.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1014', E'Parsnip', E'Fresh parsnip. Parsnips received from the best country that produces the freshest parsnips. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1014.png' ,cast(1 as bit), 100, 22.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1015', E'Garlic', E'Strong garlic cloves. Garlic received from the best country that produces the freshest garlic. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1015.png' ,cast(1 as bit), 100, 22.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1016', E'Cauliflower', E'Fresh Cauliflower. Cauliflower received from the best country that produces the freshest Cauliflowers. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1016.png' ,cast(1 as bit), 100, 27.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1017', E'Red cabbage', E'Salad red cabbage. Cabbage received from the best country that produces the freshest red cabbage. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1017.png' ,cast(1 as bit), 100, 13.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1018', E'Asparagus', E'Fresh Asparagus. Asparagus received from the best country that produces the freshest asparagus. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1018.png' ,cast(1 as bit), 100, 26.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1019', E'Artichokes', E'Fresh Artichokes. Artichokes received from the best country that produces the freshest Artichokes. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1019.png' ,cast(1 as bit), 100, 13.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1020', E'Cabbage', E'Fresh cabbage. Cabbage received from the best country that produces the freshest cabbages. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1020.png' ,cast(1 as bit), 100, 19.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1021', E'Beetroot', E'Fresh Beetroot. Beetroot received from the best country that produces the freshest Beetroots. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1021.png' ,cast(1 as bit), 100, 18.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1022', E'Tomatoes', E'Bio non-GMO Tomatoes. Tomatoes received from the best country that produces the freshest tomatoes. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1022.png' ,cast(1 as bit), 100, 26.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1023', E'Lettuce', E'Fresh lettuce. Lettuce received from the best country that produces the freshest Lettuce. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1023.png' ,cast(1 as bit), 100, 22.99, 1, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('VEG-1024', E'Celery', E'Green Celery. Celery received from the best country that produces the freshest Celery. The product is entirely BIO and hand picked and harvested just days before flown to our stores', E'assets/images/products/vegetables/vegetable-1024.png' ,cast(1 as bit), 100, 16.99, 1, NOW());


INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1000', E'Fruit - Pomegranate',  E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1000.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1001', E'Fruit - Banana', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1001.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1002', E'Fruit - Green grapes', E'Sweet, tasty grapes. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1002.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1003', E'Fruit - Pineapple', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1003.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1004', E'Fruit - Plums', E'Sweet, tasty plums. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1004.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1005', E'Fruit - Peach', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1005.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1006', E'Fruit - Watermelon', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1006.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1007', E'Fruit - Persimmon', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1007.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1008', E'Fruit - Lime', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1008.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1009', E'Fruit - Pear', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1009.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1010', E'Fruit - Cranberry', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1010.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1011', E'Fruit - Kiwi', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1011.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1012', E'Fruit - Figs', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1012.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1013', E'Fruit - Papaya', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1013.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1014', E'Fruit - Fresh Cantaloupe', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1014.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1015', E'Fruit - Red Orange', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1015.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1016', E'Fruit - Durian', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1016.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1017', E'Fruit - Honeydew Melon', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1017.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1018', E'Fruit - Cherries', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1018.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1019', E'Fruit - Lychee', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1019.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1020', E'Fruit - Apricot', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1020.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1021', E'Fruit - Mango', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1021.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1022', E'Fruit - Apples', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1022.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1023', E'Fruit - Strawberry', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1023.png' ,cast(1 as bit), 100, 18.99, 2, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('FRUIT-1024', E'Fruit - Orange', E'Sweet, tasty fruit. Freshly harvested from our world locations and would be directly send to you !', E'assets/images/products/fruits/fruit-1024.png' ,cast(1 as bit), 100, 18.99, 2, NOW());



INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1000', E'Goat Cheese', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1000.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1001', E'Kefir', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1001.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1002', E'Butter', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1002.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1003', E'Yoghurt', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1003.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1004', E'Cottage Cheese', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1004.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1005', E'Ghee', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1005.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1006', E'Emmental cheese', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1006.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1007', E'Quark', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1007.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1008', E'Milk', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1008.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1009', E'Goat Milk', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1009.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1010', E'Mozzarella Cheese', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1010.png' ,cast(1 as bit), 100, 17.99, 3, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('DAIRY-1011', E'Parmesan Cheese', E'This dairy product is created from free range livestock. It is brewed with care and is fresh when delivered to our stores. Do not wait to book it!', E'assets/images/products/dairy/dairy-1011.png' ,cast(1 as bit), 100, 17.99, 3, NOW());


INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1000', E'Amaranth', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1000.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1001', E'Buckwheat', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1001.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1002', E'Brown Rice', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1002.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1003', E'Quinoa', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1003.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1004', E'Couscous', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1004.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1005', E'Corn', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1005.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1006', E'Oats', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1006.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1007', E'Flour', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1007.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1008', E'Bulgur', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1008.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1009', E'Barley', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1009.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1010', E'White Rice', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1010.png' ,cast(1 as bit), 100, 16.99, 4, NOW());
INSERT INTO "full-stack-ecommerce"."product"  (sku, name, description, image_url, active, units_in_stock, unit_price, category_id,date_created) VALUES ('GRAIN-1011', E'Spelt', E'Grains are a great source of carbohydrates and important nutrients, including fiber B vitamins and minerals. Our grains are harvested and stored according to the best standards across the world! We carefully select continents, locations and farms! Buy now', E'assets/images/products/grains/grain-1011.png' ,cast(1 as bit), 100, 16.99, 4, NOW());

update  "full-stack-ecommerce"."product"  set rating = 1 where random() < 0.15;
update  "full-stack-ecommerce"."product"  set rating = 5 where random() < 0.15 and rating != 1;